name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: beta
    - run: dart --version
    - run: flutter --version 
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
    - name: Upload 
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: build/app/outputs/flutter-apk/app-release.apk
